version: '3'

services:
  postgres:
    image: postgres
    restart: always
    networks: [app]
    volumes:
      - /cogs/postgres/dev:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: mercury

  cogs_webapp:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    depends_on:
    - postgres
    networks: [app]
    ports:
     - "8001:8000"
    volumes:
     - /cogs/config/dev.yaml:/cogs/config.yaml
     - /cogs/uploads/dev:/uploads

networks:
  app:
    ipam:
      driver: default
      config:
      - subnet: 10.0.0.1/24
