version: '3'

services:
  postgres:
    image: postgres
    restart: always
    networks: [app]
    volumes:
      - /cogs/postgres/test:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: mercury

  # dummy_smtp:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.smtp
  #   tty: true
  #   networks: [app]

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.live
    depends_on:
    - postgres
    # - dummy_smtp
    networks: [app]
    volumes:
     - /cogs/config/test.yaml:/cogs/config.yaml
     - /cogs/uploads/test:/uploads

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    depends_on:
    - backend
    networks: [app]
    volumes:
     - /cogs/config/frontend.test.js:/usr/src/app/src/config.js

  cookie_thief:
    build:
      context: ../cookie-thief
      dockerfile: Dockerfile
    networks: [app]

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    depends_on:
     - frontend
     - backend
     - cookie_thief
    ports:
     - "8000:80"
    networks: [app]

networks:
  app:
    ipam:
      driver: default
      config:
      - subnet: 10.0.0.1/24
