version: '3'
services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - /cogs/postgres:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: mercury

  cogs_webapp:
    build: .
    ports:
     - "8000:8000"
    volumes:
     - /cogs/uploads:/uploads

