version: '3'

services:
  postgres:
    image: postgres
    restart: always
    networks: [app]
    volumes:
      - /cogs/postgres/test:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: mercury

  # dummy_smtp:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.smtp
  #   tty: true
  #   networks: [app]

  backend:
    build:
      context: ../../
      dockerfile: docker/testing/Dockerfile.app
    depends_on:
    - postgres
    # - dummy_smtp
    networks: [app]
    ports:
     - "8000:8000"
    volumes:
     - /cogs/config/test.yaml:/cogs/config.yaml
     - /cogs/uploads/test:/uploads

networks:
  app:
    ipam:
      driver: default
      config:
      - subnet: 10.0.1.1/24
