version: '3'

services:
  postgres:
    image: postgres:10
    restart: always
    networks: [app]
    volumes:
      - /cogs/postgres/test:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: mercury

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.live
    restart: always
    depends_on:
    - postgres
    networks: [app]
    volumes:
     - /cogs/config/test.yaml:/cogs/config.yaml
     - /cogs/uploads/test:/uploads
    healthcheck:
      test: ["CMD", "./backend-health_check.sh"]
      interval: 60s
      timeout: 3s
      retries: 30

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      args:
       - API_URL
       - DEVELOPER
    restart: always
    depends_on:
    - backend
    networks: [app]

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    restart: always
    depends_on:
     - frontend
     - backend
    ports:
     - "8000:80"
    networks: [app]

networks:
  app:
    ipam:
      driver: default
      config:
      - subnet: 10.0.0.1/24
